# Introduction

*An Introduction to Statistical Software*


 
Unit Questions: 

1. Why Use R? (R versus Excel)

2. What is the role of statistics in Anthropology? 

3. How do you formulate statistical questions? 

4. How do you download the program?
 
 
R is an interactive statistical program that assists in the organization and analysis of data. R is a language that exists within an environment. The word environment is associated with the R software in that R allows the user to run linear models, nonlinear regressions, time series analysis, parametric tests, etc. within an open network. The R environment is a “planned and coherent system, rather than an incremental accretion of a very specific and inflexible tools, as is frequently the case with other data analysis software.” (cran.r-project.org). 
 
R differs from **Excel** in that it technically is a more user-friendly program [see chpt XXX on spreadsheets] . While Excel may appear to be an easier software to use, if a mistake or problem occurs in Excel, it can be very hard to find the origin of the issue and correct it. R does have a learning curve and it can be intimidating, but it can be a really amazing data tool once the basics are understood. R can do everything that excel does and more. Since many people prefer to use Excel, many of the data files that you will use and upload into R will be stored in an unreadable format. In order to upload an Excel file into R, you need to save the Excel file as a csv. There are packages that allow you to *read in* an Excel file as well. 
 
The word “code” refers to the text used in computer programming language which is called the source code. Metadata is the data about data, it contains analytical descriptions about the original data.
(explain base R verses Tidy Verse)
 
There are multiple packages available for download within R. These include base R, compiler, datasets, grDevices, graphics, graid, methods, parallel, splines, stats, stats4, tcltk, tools, utils. 
 
Most of readR’s functions are concerned with turning flat files into data frames. The command read_csv( ) creates a pathway by which a file is able to be transferred and read within the R environment. 
 
It is important to note that everything within R is an object. Everything object within R is either a call, an expression, a name or a null. 
 
There is a lot of available information on how to use R but filtering through online search results can be a challenge. Almost all of your questions can be answered by a google search and there are many online forums where R experts discuss the problems that they have had with R. 
 
If posed with a problem, try not to think big as it is likely that there is a singular small problem causing your issue. 

As we learned R we found ourselves struggling a lot. Don’t think that you are alone. 


