# How Computers (and R) Think

*What is going on behind the scenes*

This chapter has a lot of background info on using computers. a lot of it is basically random tips and tricks and info that we've picked up over the years. mostly as non-computer science folks coming across terms and ideas that are basic in the comp-sci world but not in the athropology world. this is a repository of things that you might one day care about. As always a work in progress so let us know if something is missing/wrong/needs to be updated etc.


#file/folder management
https://www.tidyverse.org/articles/2017/12/workflow-vs-script/


#file types

A cool trick is to teach your computer to open various types of files  with the program you want it to use. For example, if you write in Word it probably opens this automaticlaly. but if you then get a .txt file how will it open. 


## types of files you might see in the wild and what they are

JSON - JavaScript Object Notation 


#what is an api

An API is a "application programming interface." For most of what we will use, we can think of it as a a code that lets us access information. we can send a request for the info we want 


hints for api:
load 'usethis'
run edit_r_environ()
add api there
see: https://usethis.r-lib.org/articles/articles/usethis-setup.html

#accessing/using the terminal

#computer langauges you might come across
Python

#terms 
GUI
IDE

#useful programs
Wox  - for pc. lets you open files easy and search a bit

#video and images